const g = (min, max) => {
  return min + Math.floor(Math.random() * (max - min + 1));
};
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
console.log(g(2, 8));
